### ISSUE TITLE
sophomorix-print: no pdf with latex special character in class name

### ISSUE THREAD

**Issue by kannstDuMal** [linuxmuster/sophomorix4#100]
my school is using underscores in class names in school management software.  
Printing passwords is not functioning.
In latex is _ (and others) a special character. These should be quoted while generating the .tex file.

My dirty hotfix in sophomorix-print:
```
sub latex {
    &print_title("patching undescores $output_file_basename.tex");
    my $underscore_command="cd $sophomorix_config{'INI'}{'LATEX'}{'PRINT_PATH'}; ".
                      'sed -i \'s/_/\{\\\\_\}/g\' '.$output_file_basename.".tex ".$dev_null;
    print "  * $underscore_command\n";
    system($underscore_command);

    &print_title("latex is creating $output_file_basename.dvi");
...
```

**Comment by jeffbeck** [comment]
There is already a perl module to convert strings to latex code. 
But the class field was not converted.

Thank you for reporting.

https://github.com/linuxmuster/sophomorix4/commit/bb7660a1057a2510b5bddfec396f2be6cdd65778
