### ISSUE TITLE
Faster way to get all schools

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#112]
For multischool purposes we need a command to get all available schools.

Right now I'm using ['sophomorix-school', '-i', '-jj'] which is a little on the slow site.

It would be even better if we could have a command which also provides the "School_Longname"

Later it would be good to know if a user should be able to switch between schools, I think we discussed this a long while ago and settled on reading if the user is member of the school AD Group, but I'm not sure about this.

Import right now would be to have the function to get the schools fast including the longname.

**Comment by jeffbeck** [comment]
The problem with the performance of sophomorix-school -i is:
When does a school exist?
If it is configured in sophomorix.conf?
If a school.conf file exists?
if a samba share for the school exists?
If the share has configured quota?
If the schools top AD ou exists?

sophomorix-school -i tests if a school is ready to use, thats why it is so slow.

My suggestion is to use sophomorix-query and list the OU's below OU=SCHOOLS.
