### ISSUE TITLE
Printing password Fails under special circumstances

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#114]
In the password field most special characters get escapted by a backslash. However this is not true for First and Lastname.

I ran into a problem having a Lastname Containing an underscore _ .

I fixed it by replacing the underscore with a dash, but if its possible to have underscores in the lastname / firstname this should get respected and properly commented.

**Comment by jeffbeck** [comment]
fixed from 3.80.1 onwards
