### ISSUE TITLE
Custom mail domain for extrastudents / non-students / non-teachers user

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#115]
Because there is currently no roles for "other" users (only teachers and students), we organize all of our staff in the extrastudents file. Our staff have the same mail domain like our teachers, but not like our students.

Is there a way to configure a mail domain just for extrastudents users?

I could add all of our staff as teachers, but this is not what we want (they don't need all the extra permission and shouldn't have them).

**Comment by jeffbeck** [comment]
I see your problem.
At present, the maildomain can be configured only by role.

For more configurability, it should be possible to configure the maildomain (different from the role) also by class.
Would the following new configuration solve your problem?
```
[userfile.extrastudents.csv]
      MAILDOMAIN_BY_GROUP=staff=web.de,janitor=web.de
```
All other users according to their role.

**Comment by zefanja** [comment]
>  Would the following new configuration solve your problem?

Yes! That would be great!

**Comment by jeffbeck** [comment]
I updated that in github. And will build a package in testing.
Please test asap.

**Comment by jeffbeck** [comment]
Package 3.80.1-1 in lmn7-testing

**Comment by zefanja** [comment]
I finally had the time to test it. Works great! Thank you.

**Comment by zefanja** [comment]
@jeffbeck  Any plans, when this will be released in the stable repository?

**Comment by zefanja** [comment]
@jeffbeck Could you give an update, please, when these changes will be released in the stable repo?
