### ISSUE TITLE
sophomorix-gpo wrong path for projects

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#129]
The path for drive P: which is set in the sophomorix-gpo does not contain the right path:

![grafik](https://user-images.githubusercontent.com/26460239/112439954-03749380-8d4a-11eb-8e72-53b356720d16.png)

It should be:
\\server\default-school\share\projects
instead of:
\\server\default-school\projects

**Comment by jeffbeck** [comment]
to update the gpo for a school : 
sophomorix-school --create-gpo <school>
