### ISSUE TITLE
Remove deletes users from session

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#130]
When creating a session users are saved in this session. When this user gets removed, the users still stays in the session:

![grafik](https://user-images.githubusercontent.com/26460239/113100329-8fc80000-91fb-11eb-86db-3f004a797b73.png)

This results in some nasty sophomorix erros because it cannot find the users.

My first suggestion would be to iterate all sessions when deleting users and remove them from the sessions as well.

**Comment by jeffbeck** [comment]
This is fixed after 3.81.6-1.

Please run sophomorix-kill to fix things for already deleted users.

**Comment by jeffbeck** [comment]
This will also delete deletable users.

If you do not want to delete users do the following:
sophomorix-check
rm  /var/lib/sophomorix/check-result/sophomorix.kill
sophomorix-kill
