### ISSUE TITLE
Disable Random Password -> Fixed Password should be possible to define

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#146]
When disabling random password for creating new user they get the password 'LinuxMuster!'.

This password should be possible to define via school.conf.

**Comment by jeffbeck** [comment]
I added the option DEFAULT_NONRANDOM_PWD, 
i.e. DEFAULT_NONRANDOM_PWD=Muster!
in sections

[userfile.students.csv]
[userfile.teachers.csv]
[userfile.extrastudents.csv]

to configure the password.

See: 097d623969e666f5a72cda89ba6be029593084e7
