### ISSUE TITLE
Wrong Projects Path in Drives.xml

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/sophomorix4#148]
Hi Rüdiger,
sorry if this is wrong here: maybe you can direct me to the right Package, then i open an Issue there.

The Projectsfolderpath ist wrong in
/var/lib/samba/sysvol/<myDOMAIN>/Policies/\<UUID>/User/Preferences/Drives/Drives.xml
There is writen in Line 7:
<Properties action="U" thisDrive="NOCHANGE" allDrives="NOCHANGE" userName="" path="\\server\default-school\projects" label="Projects" persistent="0" useLetter="1" letter="P"/></Drive>
But should be:
<Properties action="U" thisDrive="NOCHANGE" allDrives="NOCHANGE" userName="" path="\\server\default-school\share\projects" label="Projects" persistent="0" useLetter="1" letter="P"/></Drive>
("share" is missing in the Path).
This is like that since the Beginning: everyone needs to edit this File.
When you run 
sophomorix-school --gpo-create default-school
it resets the Drives.xml to the wrong Value...

Yours
Holger

**Comment by dorianim** [comment]
Has already been fixed in #129

**Comment by jeffbeck** [comment]
see above
