### ISSUE TITLE
User creation with suffixnumber

### ISSUE THREAD

**Issue by hagenowpaul** [linuxmuster/sophomorix4#156]
Hello,

we're supporting a school using linuxmuster v7.0 with sophomorix-samba 3.81.11-1. 

Case: A student leaves the school and decided a year later to join the school again.

We then found out, that when we recreate the user, it will get a suffix (1,2,3,...). So we use all with sophomorix-[check/update/kill/kill --killuser] commands but nothing helps. With our tests the user now have a suffixnumber 7.

We double check it with a dummy user like hans meiser and get the same situation after deleting and recreating.

In older versions we have a same situation, but the scripts deleted the user properly and the new old login didn't get a suffix.

Is there a possibility to find the samaccountname or anything else, that prevents the creation of the user with the old login?

**Comment by PLanB2008** [comment]
When a user is deleted permanently (after beeing moved to attic) this log is blocked for future use.

This prevents collision in third party services (think moodle, email etc.) Fresh user would receive newsletter the previous owner of the account has subscribed, special permission and so on. 

If you want to "free" the account you have to remove the username from the userlog:

/var/log/sophomorix/userlog/user-kill.log


This is not a bug, its a feature.

**Comment by hagenowpaul** [comment]
Thanks, that was fast and did the trick :)
