### ISSUE TITLE
create_plain_password: vague special character check

### ISSUE THREAD

**Issue by FabKre** [linuxmuster/sophomorix4#160]
While modifying special characters generation and check, I noticed the actual check is probably kind of vague:

https://github.com/linuxmuster/sophomorix4/blob/6b50cf612088f83ba43990f4ca682ed4c12cb9c2/sophomorix-samba/modules/SophomorixBase.pm#L6148
could probably be
`until ($password=~m/[!$&\(\)?]/ and`
(no commas, $ needs no escape here)

This is not an actual problem anyway, because the actual check would accept commas, which are not generated as password character.

**Comment by jeffbeck** [comment]
I tested this:  $ needs to be escaped
So I changed the line to:  
`until ($password=~m/[!\$&\(\)?]/ `

I also found out that the last character in the password character list was never selected, 
so i fixed this, too.

See https://github.com/linuxmuster/sophomorix4/commit/3e9b2d7d2a52ea48c65c4426fffd21bf9ad18b7f

For testing i have added the following option to create and show 100 passwords (no passwords set):
# sophomorix-passwd -i --random 7
