### ISSUE TITLE
[Idea] Header for user login details PDF

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#17]
This is an idea, that came to my mind: Move the date to the rigth and add a heading on the left like "Zugangsdaten"  / "Login Details" / "Access Data" / ...

![auswahl_062](https://user-images.githubusercontent.com/708888/40305575-419cbbd6-5d25-11e8-91f7-08965afc8956.png)

**Comment by jeffbeck** [comment]
Good idea, I changed it in 3.42.2-1
