### ISSUE TITLE
Space in class name

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#19]
If there is a space in the class name `sophomorix-check` outputs:

`1 users with errors in sophomorix.error`

But it does not say, where the error is. Is there another log where you could check, what error causes this result?

**Comment by jeffbeck** [comment]
The results of sophomorix-check are in:
/var/lib/sophomorix/check-result

There are files for further processing:
sophomorix.add   --> sophomorix-add
sophomorix.update --> sophomorix-update
sophomorix.kill  --> sophomorix-kill

and files which list only results
sophomorix.nochange  --> (users that are unchanged)
sophomorix.error -> (users with errors)

report.office.students.csv  -> what went wrong and why.

There you find:

ERROR in 7 a;Mauer;Heinz;10.10.1989;
   * Class 7 a not valid (special char in class 7 a)

**Comment by zefanja** [comment]
> report.office.students.csv -> what went wrong and why.

Thanks! I didn't know that this file exists. 

A detailed error report is included in the JSON result → great :+1:

**Comment by jeffbeck** [comment]
I added corrrecting (=removing whitespace in classnames), since editing these export files would be timeconsuming
