### ISSUE TITLE
[IDEA] extend sophomorix-add to add user directly

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#22]
It would be nice if you could add a user directly with sophomorix, without adding a entry in the csv first, something like

`$ sophomorix-add --firstname Max --lastname Mustermann --class 7 --dateofbirth "23.05.2005" --role student --school foo`

sophomorix could check the parameters, add it to the csv and add the user directly.

**Comment by jeffbeck** [comment]
The csv files are seen as export files from a school administration software, that will be overwritten from time to time. So modifying the file would mean that this data will be lost on the next export.

For other purposes we have the following:

1) extrastudents.csv:  not an export file. For editing by the school administrator
    Add your janitors, guest accounts ...
2) sophomorix-check --injectline "bsz.students.csv:7b;Schmid;Richard;26.04.1995;"
    which does what you want, BUT does NOT modify bsz.students.csv.
    So, a user added by this option will be tolerated right at the next sophomorix-check/update.
    But if the user later appears in bsz.students.csv, it will become a normal user.

Perhaps your issue fits in either 1) or 2) ???

**Comment by zefanja** [comment]
Thanks for your answer. So the only way to add a student is to add it to one of the csv files.

Maybe its more a question about where to look for the truth :) If I want to have a list of all students (normal and extra ones, active, tolerated, ...) I won't find that info in the csv files. I have to ask sophomorix (BTW: Is there a command for that, like getting all active/tolerated/killable students from a school?)

Because sophomorix does know the truth, it would be nice to add students directly, too (e.g. a webUI) without the need to to add the student to one of the files, run sophomorix-check and than sophomorix-add. Same applies for sophomorix-update, sophomorix-kill.

**Comment by jeffbeck** [comment]
For users, you have to ask sophomorix for the truth, which asks Active Directory and via smbcquotas the smb filesystem, config files, and .... maybe more. 

At the moment there is only an overview of user status with 
sophomorix-user -i
and
sophomorix-user -iv

**Comment by zefanja** [comment]
ok. When I see your last commits it looks like your are working/planning on a feature to get all users with a specific role, from a specific school, ... That would be great :+1:

**Comment by zefanja** [comment]
Thanks for the option to add just some classes or users in b8efb4f. It still would be nice if you could add a user directly with `sophomorix-add` (see first post), because to add a user with `sophomorix-add --user user` you need to check/parse `/var/lib/sophomorix/check-result/sophomorix.add` to get the right username.
