### ISSUE TITLE
Custom mail domain

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#23]
Is there a way to configure the pattern for mail address (like firstname.lastname@mail.com) and also the mail domain?

Best would be (for us) to be able to set it per role, because we have different mail domains for students and teachers. It would be great if they could have their proper email address in the AD.

**Comment by jeffbeck** [comment]
good idea to set it by Role.
I will add the following patterns:

These are aliases for the real mail address <user>@...
Aliases should NOT be used für all students. Because it is very likely that there will be duplicate addresses

**Comment by zefanja** [comment]
I'm not sure if I understood you correctly, but wouldn't it be possible to have the real address in the AD? We have a school domain, say example.com, our AD domain is ad.example.com, so all teachers and students email addresses are like teacher@ad.example.com. I would like to have an option, to set the mail domain per role, so it is teacher@example.com instead of ...@ad.example.com. 

We use the eMail field in AD for notifications and I don't want to setup a second mail server just to forward the LMN-generated mail addresses to their school mail, that is managed besides LMN.

**Comment by jeffbeck** [comment]
In school.conf:

per role an parameter that replaces the automatic maildomain

**Comment by jeffbeck** [comment]
Groups (adminclasses,sophomorix-group,projects, ...) also have a mail attribute entry.

What domain should be set there?

**Comment by zefanja** [comment]
Best would be different options in school.conf to set all these details. E.g. we use one mail domain for teachers, but a different one for students (@students.example.com), we also have some groups, that have a different mail domain.

**Comment by jeffbeck** [comment]
Like this:

[student]
USER_MAIL_DOMAIN=..
GROUP_MAIL_DOMAIN=

**Comment by zefanja** [comment]
Looks good :+1:

**Comment by jeffbeck** [comment]
I will change this a bit:

The parameter is always called:
MAILDOMAIN=
The location at a sophomorixRole or sophomorixType decides which maildomain ist used when creating AD entries for this sophomorixRole/sophomorixType

**Comment by jeffbeck** [comment]
https://ask.linuxmuster.net/t/namen-fuer-mailadressen/3843/3

**Comment by PLanB2008** [comment]
This seems to work just fine. I would ask for one addition (not critical right now):

What about making not only the domain configurable, but also the part before the @.

Allowing mails like sophomorixFirstname.sophomorixSN@Customdomain

?

**Comment by jeffbeck** [comment]
The mail local part (part before @) will be configurable with two parameters:

> MAIL_LOCAL_PART_SCHEME= 
>      (default ist samaccountname@)
>     Alternativen:    
>       firstname.lastname, lastname.firstname, firstname_lastname, lastname_firstname 
> MAIL_LOCAL_PART_MAP=mueller=k.mueller,maier=kpmaier  
>     (mueller,maier sind samaccountname)
> 

see: https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/config-devel/master/school.conf.master
