### ISSUE TITLE
cannot define logonScript

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/sophomorix4#24]
There is no way to define a logon script in the linuxmuster AD. In an AD environment there are two ways to do this:

1. Logon script is defined by _scriptPath_ attribute ([see MS Developer Network](https://msdn.microsoft.com/en-us/library/ms679656(v=vs.85).aspx)) in AD. But there is no such attribute in the linuxmuster AD:
`ldbsearch -H /var/lib/samba/private/sam.ldb 'scriptPath=*'`  

2. Logon script can also be set by [GPO](https://www.petri.com/setting-up-logon-script-through-active-directory-users-computers-windows-server-2008/). But using dsa.msc as global-admin user on a
 window 10 client the user object has no properties and no logon script can be set.
![lmn-win10-efi-1 auf qemu-kvm lmnhost fr to_001](https://user-images.githubusercontent.com/1845363/41648212-911b8e5c-7478-11e8-87bd-a9171c4eb15c.png)

**Comment by HappyBasher** [comment]
Value of _scriptPath_ should be _logon.cmd_ as a domain wide logon script. The script will be searched in the netlogon share. If no script is found nothing happens.

**Comment by jeffbeck** [comment]
should this script not be different by school?

**Comment by HappyBasher** [comment]
Right. Let's use the school's short name. Per default _default-school.cmd_.

**Comment by HappyBasher** [comment]
To make this work #25 has also to be fixed.

**Comment by HappyBasher** [comment]
Issue is obsolete now.
