### ISSUE TITLE
sophomorix-admin fails

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/sophomorix4#26]
During setup sophomorix-admin fails by creating global-admin:  
`sophomorix-admin --create-global-admin global-admin --password 'Muster!'`  

sophomorix version is 3.51.3-1.

[sophomorix-admin.log.txt](https://github.com/linuxmuster/sophomorix4/files/2138392/sophomorix-admin.log.txt)
[smb.conf.txt](https://github.com/linuxmuster/sophomorix4/files/2138394/smb.conf.txt)

**Comment by jeffbeck** [comment]
I didnt change anything here lately. So the setup might have changed. 

As sophomorix-admin.log.txt says:

The is no configured share for default-school

net conf list should show this shares:

[linuxmuster-global]
	path = /srv/samba/global
	comment = Share for school global
	guest ok = yes
	read only = no

[default-school]
	path = /srv/samba/schools/default-school
	comment = Share for school default-school
	guest ok = yes
	read only = no

**Comment by HappyBasher** [comment]
Right, the default-school share was not created. Closed.
