### ISSUE TITLE
Adding or Updating users takes a long time

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#30]
Currently adding or updating one users takes roughly 12s on my system. Its not the fastest system, but is this normal? Maybe its because the sophomorix commands are very verbose, but for bigger schools (>500 users) it will take almost 90min to add or update the students/teachers. This is quite long IMHO (and not an urgent issue).

**Comment by jeffbeck** [comment]
on my virtual test system its about 1-2s per user

**Comment by jeffbeck** [comment]
I close this issue, cause it cannot be repeated on any of my systems
