### ISSUE TITLE
sophomorix-kill --killuser should delete entry from csv, too

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#31]
When you delete a user with `sophomorix-kill --killuser user` it is deleted from AD, but not from the csv, so next time you run `sophomorix-add` it will be added again.

It would be nice if `sophomorix-kill` would delete the entry in the csv, too.

**Comment by jeffbeck** [comment]
This is the intended behaviour.

**Comment by zefanja** [comment]
OK, I understand that, but I still struggle to understand why sophomorix works that way.

You can remove users with one command, you can do almost everything with just one sophomorix command, but to update or to add a user you have to add / edit an entry in a CSV file first. 

Its good to have this option for bulk imports, but, as I said in the other issue, it should be possible to add or update users with just one command, too and without editing csv files.

**Comment by jeffbeck** [comment]
Keep that in mind for later versions.
