### ISSUE TITLE
[Question] How to use sophomorix-query to search for sophomorixStatus

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#32]
Currently `sophomorix-query --student` returns all students (regardless of sophomorixStatus). What is the correct command to search for all users that are tolerated (`sophomorixStatus=T`)?

How can I specify that I want to search for that specific field?

**Comment by jeffbeck** [comment]
sophomorix-query is specifically desings for performance.
(i.e. drop down menues for the webui, ...)

It does not read the overall configuration to save time, it just connects, and delivers data.

For an overview over tolerated users, ...  

1) there must be specific commands programmed.

or 

2) maybe a configurable filter (using ldap filter syntax)
The second option will be better for debugging, I guess. What do you think?

**Comment by zefanja** [comment]
Second option would be good, because it is more flexible. On the other side there should be an option to for `--student` to specify what students you are looking for (at least active and tolerated students).

**Comment by PLanB2008** [comment]
I'm with zefanja. We definitely need this for the webui as well. Especially for dropdowns etc. its necessary to know if a student is active or tolerated.

**Comment by jeffbeck** [comment]
sophomorix-query has the additional parameter status to limit the search to one or more statii

fixed in V-3.60.16-1
