### ISSUE TITLE
school.conf wrong format

### ISSUE THREAD

**Issue by netzint** [linuxmuster/sophomorix4#34]
there is a mix of spaces and tabs in die defaul-school.conf

![image](https://user-images.githubusercontent.com/10708981/43884971-dbd9245c-9bb7-11e8-95d9-a59e52bd3b8f.png)

**Comment by jeffbeck** [comment]
This file does not come from sophomorix installation (see the header)

default-school/school.conf is copied by sophomorix-postinst

To fix this, do:

`# rm /etc/linuxmuster/sophomorix/default-school/school.conf`
`# sophomorix-postinst`

Then the file is recreated.

**Comment by jeffbeck** [comment]
closed together with #33
