### ISSUE TITLE
Users get removed from group if class is changed

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#39]
When you add a user (eg. teacher) to a class group

by  sophomorix-group --addmembers hulk --group 2b

 and the class is updated afterwards (students removed, added or changed) the teacher gets removed from this group

**Comment by jeffbeck** [comment]
sophomorix-group adds a user to a group (very similar to samba-tool, only the membership attributes are updated)

To add a **teacher** as an **administrator**(for the class) to a **adminclass** you must use:

sophomorix-class --addadmins hulk --class 2b

This updates also the sophomorixAdmins attribute, and the admins are kept in the class, when adding/... new users to the class

**Comment by PLanB2008** [comment]
Can you add a Batch feature for this so we are able to add a user to several groups as an administrator  e.g:

1) `sophomorix-class --addadmins hulk --class 2b,10a,3c`

and if possible (not needed right now) the other way around:

2) `sophomorix-class --addadmins hulk,at,rd --class 2b`

**Comment by jeffbeck** [comment]
Nr. 2) is batched already (see help)

Nr 1) has to be done.

**Comment by jeffbeck** [comment]
fixed in sophomorix 3.60.15-1
