### ISSUE TITLE
Feature Request: sophomorix-query --printer

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#40]
We need a way to determine printergroups.

At the moment theres no sophomorix command to show which printers exist so we can't show users which printers are available to subscribe.

**Comment by jeffbeck** [comment]
as from sophomorix 3.60.13 on:

Lists the computers that are printers (sophomorixRole=printer):

`sophomorix-query   --printer -j (--comp-full)`

The associated groups can be listed with:

`sophomorix-query   --printergroup -j (--group-full) (--group-members)`

**Comment by jeffbeck** [comment]
Please close this issue if you can find what you want

**Comment by PLanB2008** [comment]
The secon query was the one I needed. This seems to work and is already used in the groupmembership module.
