### ISSUE TITLE
school.conf extraclasses

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#41]
There's a section extraclasses in school conf. This section lacks the data all other sections have.

I suggest either we drop this completely or we handle extraclasses like alle other csv files and need to define Encoding and so on.

[classfile.extraclasses.csv]
# is a file extraclasses needed?~
# or can we configure these classes here?~

**Comment by jeffbeck** [comment]
In a long term view, it is better to handle extraclasses  with a new command `sophomorix-extraclass`

This command will be able to modify necessary stuff in these classes (password, numer of users, ....)

At the moment the file extraclasses has some fields that are updated by -check,-update but others are not (It's the behaviour of linuxmuster.net 6.2, so its OK at the moment)

**Comment by jeffbeck** [comment]
sophomorix-extraclass is in a usable state from 3.74.14 or later.

You can create and delete extraclasses without config file by using command line options.

see

sophomorix-extraclass --help
