### ISSUE TITLE
Empty string key in JSON Output

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#42]
Since the last update I get empty keys in the sophomorix-query json output:

![grafik](https://user-images.githubusercontent.com/26460239/45946184-745b5900-bff0-11e8-9ff7-4a555296dfec.png)

I added the output I get by running the command:
sophomorix-query --schooladministrator --user-full -j 2> emptyStringKey.json 
[emptyStringKey.zip](https://github.com/linuxmuster/sophomorix4/files/2410361/emptyStringKey.zip)

These empty lists leads to errors in the WEBUI I dont know how to handle. The parser has options to handle these empty lists but fails later. 

Are these necessary or a bug? 

Can you reproduce this error? I'm not sure if this is an error in my dev environment.

**Comment by jeffbeck** [comment]
This is a bug introduced in last update (to fix another problem)

**Comment by jeffbeck** [comment]
Fixed in 3.60.14-1
