### ISSUE TITLE
Batch feature for sophomorix-class

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#43]
addition to #39 
Can you add a Batch feature for this so we are able to add a user to several groups as an administrator e.g:

sophomorix-class --addadmins hulk --class 2b,10a,3c

and if possible (not needed right now) the other way around:

sophomorix-class --addadmins hulk,at,rd --class 2b

**Comment by jeffbeck** [comment]
fixed in sophomorix 3.60.15-1
