### ISSUE TITLE
Class Share Folder are not removed

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#44]
Class folders are not deleted if no members are left in a class.

![grafik](https://user-images.githubusercontent.com/26460239/46022160-59691180-c0e2-11e8-9e65-0b8789d9de07.png)

**Comment by jeffbeck** [comment]
That a correct behaviour. Classes are empty for a while in some schools 
(students leave at the end of a "Block" before summer break - New students come to a new "Block" in the next year a while after summer break)

Maybe we  could delete a class that stays empty for i.e. 400 days automatically per cron job
