### ISSUE TITLE
sophomorix-transfer

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#49]
We need a way to share data with sophomorix-transfer without creating the transfer subfolder.

Indeed I think share data option

  sophomorix-transfer --from-unix-path /srv/upload/... --to-user <user1>,<user2>-exam, ... --subdir <dir>

woult do the job - but this is based on the unix path. I would prefear something which is more versatile.

At the moment I share files like so:

sophomorixCommand = ['sophomorix-transfer', '-jj', '--collect-copy', '--from-user', sender, '--to-user', receiver, '--file', fileListCSV]

where fileListCSV are comma seperated strings like

transfer/course1,transfer/courseb

This results in a complex path when files are shared like:

(hulk == teacher, scheffri == student)

/srv/samba/schools/default-school/students/10a/scheffri/transfer/hulk/transfer

My suggestion is to have a command like

sophomorix-transfer --share

which just takes the file I want to share and copys it to 

/srv/samba/schools/default-school/students/10a/scheffri/transfer/hulk

In addition I have a suggestion for collecting data. Wouldn't it make sense to put these data in a subfolder when collecting like:

/srv/samba/schools/default-school/teachers/homes/hulk/transfer/SESSIONNAME/user/

I could create this folder or name it but I'm not sure how to handle this in a clean way without puting logic in the WEBUI.

**Comment by jeffbeck** [comment]
The original idea to share data is:

1) use the webui to select files and upload it to the server
2) see on the server what was upoaded
3) sophomorix-transfer --from-unix-path /srv/upload/... --to-user ,-exam, ... --subdir

**Comment by jeffbeck** [comment]
The transfer folder is created at every user, is undeleteabe and can be repaired.

**Comment by PLanB2008** [comment]
Thats only part of the feature set. We also decided to let the teacher share files they already have in their transfer folder.
I remember we decided to support both ways.

**Comment by jeffbeck** [comment]
The --distrubute option is missing in sophomorix-transfer.
It is waiting for a tool (on the lmn7 server) that supports Server-Side-Copy:

https://wiki.samba.org/index.php/Server-Side_Copy

To my knowledge, this tool is still missing.

**Comment by jeffbeck** [comment]
We check with upstream support for a server (ubuntu 18.04) based tool that:

1. copies recursively via smb:// from one share to another
2. copies within a smb share via smb:// and uses server-side-copy

The shares should not be mounted to do this.

**Comment by jeffbeck** [comment]
this is implemented by sophomorix-transfer --scopy ...
