### ISSUE TITLE
sophomorix-admin fails on creating users during setup

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/sophomorix4#51]
Error message is among other things:
ERROR   -1: WEBUI is NOT valid in section role.student of /etc/linuxmuster/sophomorix/default-school/school.conf!

see log:
[setup.samba-users.log](https://github.com/linuxmuster/sophomorix4/files/2437340/setup.samba-users.log)

school.conf:
[school.conf.txt](https://github.com/linuxmuster/sophomorix4/files/2437352/school.conf.txt)

**Comment by jeffbeck** [comment]
Please do what the error message says:
WEBUI is NOT valid in section role.student of /etc/linuxmuster/sophomorix/default-school/school.conf!

--> remove WEBUI=.... from the file above
(was renamed to WEBUI_PERMISSIONS=)

The allowed section/parameters is configured in the master file:

https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/config-devel/master/school.conf.master
