### ISSUE TITLE
sophomorix-query with --quota switch

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/sophomorix4#53]
add quota (used/max) to user output.
Check how fast this is.

**Comment by jeffbeck** [comment]
I added quota usage in 3.60.20-1 (using smbprotocol with smbcquotas)

This takes about 0,5 seconds on my test system per user.

`sophomorix-query --teacher --sam <user>  --user-full -j --quota`

Please verify.

**Comment by kiarn** [comment]
I'm using it into the WebUI, and it seems to work.

**Comment by jeffbeck** [comment]
OK
