### ISSUE TITLE
examuser creation: cloning of password does not work

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/sophomorix4#54]
When creating examuser accounts, they seem to have set their firstpasswird. 

The password hash of `<user>` should be copied to the `<user-exam>`

**Comment by jeffbeck** [comment]
Ich habe das gerade getestet.

Das tut bei mir.

Ich habe in sophomorix-passwd password test eingebaut:

sophomorix-passwd --test-login -u mueller-exam --password Muster!

man nimmt das password des users mueller  und testet dann auf den exam account: Tut bei mir

Ich mach ein Paket mit den password tests: 3.60.21-1

**Comment by PLanB2008** [comment]
Still doesn't work. If I check the password via sophomorix-passwd it passed the test.

Nevertheless I can't login using thiss password but the initial Password LinuxMuster! works...

![peek 2018-10-15 13-06](https://user-images.githubusercontent.com/26460239/46947491-40b5a100-d07b-11e8-83e0-174b04c282aa.gif)

**Comment by jeffbeck** [comment]
How can I pause the video? Or is it a gif?


`sophomorix-passwd --test-login -u mueller-exam --password Muster!`

uses the return Value of :

`wbinfo --pam-logon=user%'testpassword' `

Can you issue the wbinfo command directly?

I have no clue:(

**Comment by PLanB2008** [comment]
Its a gif, indeed. Perhaps I should provide a video next time. 

After the last update I do not get the firstpassword set in the base account as a result of 
     sophomorix-user --info -j -u ilkesju-exam
I just receive 
    ---
I just doublechecked the issue. It doensn't matter if I use the initial-password or a user changed password. It always stays LinuxMuster!

Using
    wbinfo --pam-logon=user%'testpassword'

I'm not able to get any account successful checked. Probably I don't get how to escape special characters.

**Comment by jeffbeck** [comment]
> After the last update I do not get the firstpassword set in the base account as a result of
> sophomorix-user --info -j -u ilkesju-exam
> I just receive ---

Before the update, there was the default passwort set in the attribute sophomorixFirstPassword. Since the password was cloned this was missleading. So I set the  sophomorixFirstPassword to ---

Maybe its better to copy sophomorixFirstPassword from <user> to <user>-exam when creating the exam account???
How do you set the firstpassword on a exam user?


Can you check if cloning of the password with `sophomorix-passwd` works(see `sophomorix-passwd -h`)?

`wbinfo --pam-logon=user%'testpassword'`

works on my system.

**Comment by jeffbeck** [comment]
From 3.60.25-1 on I'm cloning:

- unicodePwd
- supplementalCredentials

this seems to work for pam and kerberos login, tested with:

`# wbinfo --pam-logon=user%'testpassword'`
`# wbinfo --krb5auth=user%'testpassword'`

Please confirm that windows 10 login works after cloning

**Comment by PLanB2008** [comment]
This seems to work, now. Great job.
