### ISSUE TITLE
Question about date of birth

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/sophomorix4#56]
A date of birth in future seems to be valid for 2020, but not for 2030. Why?

**Comment by jeffbeck** [comment]
For some reason (which I dont remember) this range as valid birth years:

1) if the year is given as one or twodigits, ist is converted like this:

my %convert_year = qw(
     1     2001          01    2001
     2     2002          02    2002
     3     2003          03    2003
     4     2004          04    2004
     5     2005          05    2005
     6     2006          06    2006
     7     2007          07    2007
     8     2008          08    2008
     9     2009          09    2009
     10    2010          11    2011
     12    2012          13    2013
     14    2014          15    2015
     16    2016          17    2017
     18    2018          19    2019
     20    2020          21    2021
     22    2022          23    2023
     24    2024          25    2025
     26    2026          27    2027
     28    2028          29    2029
     30    1930          31    1931
     32    1932          33    1933
     34    1934          35    1935
     36    1936          37    1937
     38    1938          39    1939
     40    1940          41    1941
     42    1942          43    1943
     44    1944          45    1945
     46    1946          47    1947
     48    1948          49    1949
     50    1950          51    1951
     52    1952          53    1953
     54    1954          55    1955
     56    1956          57    1957
     58    1958          59    1959
     60    1960          61    1961
     62    1962          63    1963
     64    1964          65    1965
     66    1966          67    1967
     68    1968          69    1969
     70    1970          71    1971
     72    1972          73    1973
     74    1974          75    1975
     76    1976          77    1977
     78    1978          79    1979
     80    1980          81    1981
     82    1982          83    1983
     84    1984          85    1985
     86    1986          87    1987
     88    1988          89    1989
     90    1990          91    1991
     92    1992          93    1993
     94    1994          95    1995
     96    1996          97    1997
     98    1998          99    1999
);

2) and this 4 digit years are valso valid

for( my $year = 1930 ; $year < 2029 ; $year++) {
    $convert_year{$year}=$year;
}

**Comment by zefanja** [comment]
The question for me, too, is: Why are date of births in future allowed anyway?
