### ISSUE TITLE
Allow empty participant string in sophomorix-session

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#58]
Related to:
https://github.com/linuxmuster/linuxmuster-webui7/issues/46

I need the option to pass an empty participant command to sophomorix session like:

    sophomorix-session --session 2018-09-28_11-03-23 -j --participants ''

**Comment by jeffbeck** [comment]
Have you also tried the doublequote? `""`

**Comment by PLanB2008** [comment]
Just tried. Doesn't work either.

**Comment by jeffbeck** [comment]
Fixed in 3.60.22-1

**Comment by PLanB2008** [comment]
Tested and approved
