### ISSUE TITLE
Can't add user to printergroups anymore

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#59]
1    sophomorix-query --printer -j --comp-full

gives me a list of all my printers:

          "B6-437-P01$" : {
             "sophomorixStatus" : "P",
             "userAccountControl" : "4096",
             "dNSHostName" : "B6-437-P01.linuxmuster.lan",
             "sophomorixDnsNodename" : "b6-437-p01",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "sophomorixAdminClass" : "b6-437",
             "memberOf" : [
                "CN=b6-437,OU=b6-437,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "name" : "B6-437-P01",
             "sAMAccountName" : "B6-437-P01$",
             "sophomorixRole" : "printer",
             "sophomorixAdminFile" : "devices.csv",
             "displayName" : "Computer B6-437-P01",
             "sn" : null,
             "sophomorixSchoolname" : "default-school"
          },
          "B6-422-P01$" : {
             "displayName" : "Computer B6-422-P01",
             "sophomorixAdminFile" : "devices.csv",
             "sn" : null,
             "sophomorixRole" : "printer",
             "sophomorixSchoolname" : "default-school",
             "sophomorixDnsNodename" : "b6-422-p01",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "dNSHostName" : "B6-422-P01.linuxmuster.lan",
             "userAccountControl" : "4096",
             "sophomorixStatus" : "P",
             "name" : "B6-422-P01",
             "sAMAccountName" : "B6-422-P01$",
             "memberOf" : [
                "CN=b6-422,OU=b6-422,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "sophomorixAdminClass" : "b6-422"
          },
          "B7-107-P01$" : {
             "sophomorixSchoolname" : "default-school",
             "displayName" : "Computer B7-107-P01",
             "sophomorixAdminFile" : "devices.csv",
             "sn" : null,
             "sophomorixRole" : "printer",
             "sAMAccountName" : "B7-107-P01$",
             "name" : "B7-107-P01",
             "memberOf" : [
                "CN=b7-107,OU=b7-107,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "sophomorixAdminClass" : "b7-107",
             "sophomorixDnsNodename" : "b7-107-p01",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "dNSHostName" : "B7-107-P01.linuxmuster.lan",
             "userAccountControl" : "4096",
             "sophomorixStatus" : "P"
          },
          "B6-421-P01$" : {
             "sophomorixAdminFile" : "devices.csv",
             "sn" : null,
             "displayName" : "Computer B6-421-P01",
             "sophomorixRole" : "printer",
             "sophomorixSchoolname" : "default-school",
             "userAccountControl" : "4096",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "sophomorixDnsNodename" : "b6-421-p01",
             "dNSHostName" : "B6-421-P01.linuxmuster.lan",
             "sophomorixStatus" : "P",
             "name" : "B6-421-P01",
             "sAMAccountName" : "B6-421-P01$",
             "sophomorixAdminClass" : "b6-421",
             "memberOf" : [
                "CN=b6-421,OU=b6-421,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ]
          },
          "B5-512-P01$" : {
             "sophomorixRole" : "printer",
             "sophomorixAdminFile" : "devices.csv",
             "displayName" : "Computer B5-512-P01",
             "sn" : null,
             "sophomorixSchoolname" : "default-school",
             "sophomorixStatus" : "P",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "sophomorixDnsNodename" : "b5-512-p01",
             "dNSHostName" : "B5-512-P01.linuxmuster.lan",
             "userAccountControl" : "4096",
             "memberOf" : [
                "CN=b5-512,OU=b5-512,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "sophomorixAdminClass" : "b5-512",
             "sAMAccountName" : "B5-512-P01$",
             "name" : "B5-512-P01"
          },
          "B6-329-P01$" : {
             "sophomorixStatus" : "P",
             "dNSHostName" : "B6-329-P01.linuxmuster.lan",
             "sophomorixDnsNodename" : "b6-329-p01",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "userAccountControl" : "4096",
             "memberOf" : [
                "CN=b6-329,OU=b6-329,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "sophomorixAdminClass" : "b6-329",
             "name" : "B6-329-P01",
             "sAMAccountName" : "B6-329-P01$",
             "sophomorixRole" : "printer",
             "sn" : null,
             "sophomorixAdminFile" : "devices.csv",
             "displayName" : "Computer B6-329-P01",
             "sophomorixSchoolname" : "default-school"
          },
          "B5-313-P01$" : {
             "name" : "B5-313-P01",
             "sAMAccountName" : "B5-313-P01$",
             "memberOf" : [
                "CN=b5-313,OU=b5-313,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "sophomorixAdminClass" : "b5-313",
             "dNSHostName" : "B5-313-P01.linuxmuster.lan",
             "sophomorixDnsNodename" : "b5-313-p01",
             "sophomorixCreationDate" : "20180827120826.0Z",
             "userAccountControl" : "4096",
             "sophomorixStatus" : "P",
             "sophomorixSchoolname" : "default-school",
             "sn" : null,
             "sophomorixAdminFile" : "devices.csv",
             "displayName" : "Computer B5-313-P01",
             "sophomorixRole" : "printer"
          },
          "B6-438-P01$" : {
             "sophomorixSchoolname" : "default-school",
             "sophomorixRole" : "printer",
             "sophomorixAdminFile" : "devices.csv",
             "sn" : null,
             "displayName" : "Computer B6-438-P01",
             "sophomorixAdminClass" : "b6-438",
             "memberOf" : [
                "CN=b6-438,OU=b6-438,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan",
                "CN=printer,OU=Devices,OU=default-school,OU=SCHOOLS,DC=linuxmuster,DC=lan"
             ],
             "name" : "B6-438-P01",
             "sAMAccountName" : "B6-438-P01$",
             "sophomorixStatus" : "P",
             "userAccountControl" : "4096",
             "dNSHostName" : "B6-438-P01.linuxmuster.lan",
             "sophomorixDnsNodename" : "b6-438-p01",
             "sophomorixCreationDate" : "20180827120826.0Z"
          }
       },
       "LISTS" : {
          "USER" : [],
          "ROOM" : [],
          "COMPUTER" : [
             "B5-313-P01$",
             "B5-314-P01$",
             "B5-315-P01$",
             "B5-405-P01$",
             "B5-406-P01$",
             "B5-501-P01$",
             "B5-502-P01$",
             "B5-504-P01$",
             "B5-505-P01$",
             "B5-512-P01$",
             "B5-513-P01$",
             "B5-514-P01$",
             "B5-515-P01$",
             "B5-516-P01$",
             "B5-517-P01$",
             "B6-222-P01$",
             "B6-224-P01$",
             "B6-321-P01$",
             "B6-324-P01$",
             "B6-329-P01$",
             "B6-331-P01$",
             "B6-333-P01$",
             "B6-334-P01$",
             "B6-421-P01$",
             "B6-422-P01$",
             "B6-425-P01$",
             "B6-427-P01$",
             "B6-437-P01$",
             "B6-438-P01$",
             "B6-524-P01$",
             "B6-525-P01$",
             "B7-106-P01$",
             "B7-107-P01$",
             "B7-110-P01$",
             "B7-112-P01$"
          ],
          "GROUP" : []
       },
       "COUNTERS" : {
          "GROUP" : 0,
          "COMPUTER" : 35,
          "ALL" : 0,

But adding a user to these groups fails: 
sophomorix-group --addmembers hulk --group b5-314-p01 -j

    #### ERROR retrieving group b5-314-p01: 0 group found.                    ####
    # JSON-begin
    {
       "JSONCOMMENT" : "---",
       "JSONINFO" : "RESULT",
       "SCRIPTNAME" : "sophomorix-group",
       "OUTPUT" : [
          {
             "NUMBER" : -1,
             "MESSAGE_EN" : "ERROR retrieving group b5-314-p01: 0 group found.",
             "TYPE" : "ERROR",
             "MESSAGE_DE" : "ERROR retrieving group b5-314-p01: 0 group found."
          }
       ]
    }
    
    # JSON-end

This did work already? Can you reproduce this?

**Comment by jeffbeck** [comment]
The printer groups are new, so this might have never worked.
I added the management of proups of type printer in 3.60.22-1

**Comment by PLanB2008** [comment]
Well, I was able to put user in these printer groups before. I'll do some tests.

**Comment by PLanB2008** [comment]
Okay this seems to work now. Gonna close the issue till something unexpected happens.
