### ISSUE TITLE
Need consistent return keys

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#60]
I know theres still a low of work in the output section. One problem hit me right now:

    # JSON-begin
    {
       "OUTPUT" : [
          {
             "LOG" : "/usr/sbin/sophomorix-class terminated regularly",
             "TYPE" : "LOG"
          }
       ],
       "JSONINFO" : "RESULT",
       "JSONCOMMENT" : "---",
       "SCRIPTNAME" : "sophomorix-class"
    }
    
    # JSON-end
    
    #### ERROR retrieving class 123: 0 class found.                           ####
    # JSON-begin
    {
       "JSONCOMMENT" : "---",
       "SCRIPTNAME" : "sophomorix-class",
       "JSONINFO" : "RESULT",
       "OUTPUT" : [
          {
             "MESSAGE_DE" : "ERROR retrieving class 123: 0 class found.",
             "MESSAGE_EN" : "ERROR retrieving class 123: 0 class found.",
             "NUMBER" : -1,
             "TYPE" : "ERROR"
          }
       ]
    }
    
    # JSON-end

Its kind of hart to differ the output. I could look for the TYPE Value and decide whether its an error or log output - but then there are different Messages to show.

Shouldn't we also print LOG  Messages as MESSAGE_EN?

**Comment by jeffbeck** [comment]
is this from one script run or are you comparing different outputs?
What was/were the command/s?

**Comment by PLanB2008** [comment]
Sorry for the lack of information. This was the command:
    sophomorix-class --addadmins hulk --class  6b -j 
    sophomorix-class --addadmins hulk --class 123 -j 

so once with an existing group and once with a non existing group.

In the current usecase it would be nice if the json tree scheeme  would match with

    sophomorix-group --addmembers hulk --group 6b -j 

as well.

**Comment by jeffbeck** [comment]
At the moment the output:

"LOG" : "/usr/sbin/sophomorix-class terminated regularly",

means, that everything is done what was intended to do (sort of return 0).

Are you missing a log line that says: "user  hulk successfully added to 6b"??

**Comment by PLanB2008** [comment]
The problem I have is the inconsistence of the keys. Once sophomorix returns
json I've to determine which type I receive by parsing the TYPE string. 
Based on this I've to decice wheter its an error or a  info message.

This part is okay, but on top there are different keys, providing the output: LOG and MESSAGE.

Maybe I just get it wrong and the successful command is just missing a MESSAGE_DE / MESSAGE_EN
section.

I'm just curious about the right way to handle the return output.
