### ISSUE TITLE
Samba Attribute Home Directory should be changed

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#72]
We ran into some serious issues having the domain name as unc path for the home directory using windows 10.
A fix was to change the path from domain  like this:

         "homeDirectory" : "\\\\linuxmuster.lan\\default-school\\teachers\\hulk",

to server unc path:

         "homeDirectory" : "\\\\server.linuxmuster.lan\\default-school\\teachers\\hulk",

This should be the default from now on and shouldn't break anything.

**Comment by jeffbeck** [comment]
fixed in 3.68.0-1 or later

**Comment by jeffbeck** [comment]
Run:

sophomorix-check
and 
sophomorix-update

to update users
