### ISSUE TITLE
Encoding setting for Extra Courses results in sophomorix-check error

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/sophomorix4#77]
In the WebUI settings it is possible to set encoding for Extra courses. Once this is done, however, adding new users is not possible, because ENCODING is not allowed for extraclasses in sophomorix-check.

![Bildschirmfoto 2019-07-24 um 09 24 25](https://user-images.githubusercontent.com/48863382/61773379-d5acae00-adf4-11e9-9d56-8441e2d5393a.png)

**Comment by zefanja** [comment]
This is a webUI issue that allows to set the encoding for extra courses which are "not a valid section in extraclasses".

**Comment by RolandBBerlin** [comment]
Issue in WebUI opened
