### ISSUE TITLE
Feature Request: Hook Scripts

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#80]
We need an option to run custom scripts after running

  sophomorix-add
  sophomorix-kill
  sophomorix-update

Could you implement a hookscript which will allow us to run custom scripts?

**Comment by jeffbeck** [comment]
https://github.com/linuxmuster/sophomorix4/wiki/Hooks

**Comment by PLanB2008** [comment]
Didn't know about this. I'll close the issue myself.
