### ISSUE TITLE
How to set quota through school.conf ?

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/sophomorix4#81]
Hello @jeffbeck 

I want to set quota for all teachers, for example.
I've done the following : 

```
vim /etc/linuxmuster/sophomorix/default-school/school.conf --> change value for QUOTA_DEFAULT_GLOBAL in [role.teacher]
sophomorix-quota
```

But the quotas are not updated in the ldap tree.
Is it necessary to do another step to set this ?

Thanks !

Arnaud

**Comment by kiarn** [comment]
Ok, I can set default quota for an user with :

    sophomorix-user -u USER --quota default-school:---
    sophomorix-quota

and then, the USER get the value specified in school.conf.
But if I change the default value quota afterwards for default-school in school.conf and then run `sophomorix-quota`, it will not be updated for this user.

I mean : if I want to change the default quota for share default-school for all teachers, do I have to run a `sophomorix-user -u USER --quota default-school:---` first for all teachers, or is there a faster way to do it ?

Thanks !

**Comment by jeffbeck** [comment]
I made a fix in sophomorix 3.70.7-1 in lmn-testing repo


Please do the following on your TESTSERVER:

1. `sophomorix-quota --nondefault`   
to display and remember the userquota that are not default. All will show up, remember them by the different value
2. `sophomorix-user --quota-reset-teachers default-school` (reset to default)
3. `sophomorix-user --quota-reset-students default-school` (reset to default)
4.  `sophomorix-quota` to set the quota on the shares

Pleas verify that the no user has an individual quota:
`sophomorix-user --user USER -iv | grep sophomorixQuota`

should display --- at the second part of the quota values

Set individual quota from 1. again

**Comment by jeffbeck** [comment]
Please test also #89

**Comment by kiarn** [comment]
Perfect, thank you for this fix @jeffbeck !
After that, change the value in `school.conf` and then run `sophomorix-quota` set the right for all users having default values.
