### ISSUE TITLE
Quota format answer for sophomorix-query

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/sophomorix4#82]
Hello,

I don't the same format for Cloud and Mail ( units only present in `sophomorixCloudQuotaCalculated` ) : 

```
$ sophomorix-query --sam dr --user-full --quota-usage -j 2>&1 | grep Quota 
         "sophomorixMailQuota" : "---:---:",
         "sophomorixMailQuotaCalculated" : "306",
         "sophomorixCloudQuotaCalculated" : "2506 MB",
```
Thanks 

Arnaud

**Comment by jeffbeck** [comment]
sophomorixCloudQuotaCalculated is prepared for cloud use (i.e. Nextcloud). Nextcloud expects is with the unit MB.

sophomorixMailQuotaCalculated is used by postfix or dovecot, which expects it as a number (and adds the uini MiB)

**Comment by kiarn** [comment]
Ok, then I have to adapt the output for the landing page. If it's stay so, it's not a problem.
