### ISSUE TITLE
Extraclasses not working

### ISSUE THREAD

**Issue by foer** [linuxmuster/sophomorix4#84]
After creating an extra class sophomorix.add exits with the following error:

`ERROR: /usr/share/sophomorix/devel/ntacl/adminclass-homes.ntacl.template not found/readable`

The file exists:
`-rw-r--r-- 1 root root 308 Sep 9 18:36 /usr/share/sophomorix/devel/ntacl/adminclass.homes.ntacl.template`

The class is created but not the members of the class.
This looks like a bug.

Dominik

**Comment by PLanB2008** [comment]
Duplicate of #87
