### ISSUE TITLE
sophomorix-check  more output

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#86]
Running sophomorix-check we receive following:
`
      "UPDATE" : { 
         "hagerma" : {
            "sophomorixStatus" : {
               "NEW" : "T",
               "OLD" : "U"
            }
         },
         "albertfl" : {
            "sophomorixStatus" : {
               "OLD" : "U",
               "NEW" : "T"
            }
         }
      },
`

Which we use to create this view:

![grafik](https://user-images.githubusercontent.com/26460239/64965389-2e507280-d89d-11e9-9ad7-e2796c2ab812.png)

Would it be possible to include other changing attributes as well? In this case we've the maill  attribute changing:

```
update of jamalya:
   jamalya@linuxmuster.lan
   jamalya@@fast-planlos.de
update of michelja:
   michelja@linuxmuster.lan
   michelja@@fast-planlos.de
```

**Comment by jeffbeck** [comment]
Fixed in 3.70.6-1
