### ISSUE TITLE
Sophomorix-exam > transfer all data

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#88]
When a teacher ends an exam using the webui it calls following command:

`'sophomorix-exam-mode', '--unset', '--subdir', 'transfer/collected/'+now+'-'+sessionName+'/exam', '-j', '--participants', noExamModeListCSV`

where noExamModeListCSV is a csv list containing the users leaving exam mode.

In this case only data a student saved in transfer/ subfolder are collected. I suggest ending an exam moves all data a user created to the teacher.

**Comment by jeffbeck** [comment]
Please try with
 
--subdir ""

(or without --subdir option)

**Comment by PLanB2008** [comment]
--subdir defines the destination folder, not the source folder.

**Comment by PLanB2008** [comment]
This does still exist and is an urgent error.

There is the possibility of dataloss if exam users save their output not in the transfer folder.

**Comment by jeffbeck** [comment]
The workflow right now is the following:

1) collection during a KA: just use the transfer folder as input.
--> teach everybody what the transfer folder is for.

2) Terminating the KA: collect the whole home folder (just in case)


Out teachers are lerning 1) and changing it might have a strange impact.

**Comment by jeffbeck** [comment]
Collecting during "Unterricht" is limited to transfer. Like exam in the Moment.

Collectin home folder in exam and transfer folder in normal Unterricht would be strange.

**Comment by PLanB2008** [comment]
This issue is about ending the exam.

When terminating the exam the whole home is NOT collected but just the transfer folder. This is what this issue is about.

**Comment by jeffbeck** [comment]
Is fixed in sophomorix 3.74.14 or later
