### ISSUE TITLE
sophomorix-query VS sophomorix-user for quota.

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/sophomorix4#89]
Hello,

To extend https://github.com/linuxmuster/sophomorix4/issues/81, I get different results between these 2 commands :

    # sophomorix-query --sam USER --user-full --quota-usage -j
    ...
      "QUOTA_USAGE_BY_SHARE": {
    "default-school": {
      "FULL_USER": "UNPEUD\\dr                     ", 
      "USED": "350248960", 
      "SOFT_LIMIT_MiB": 2004.8, 
      "HARD_LIMIT_MiB": 2506, 
      "SOFT_LIMIT": "2102184960", 
      "USED_MiB": 334, 
      "HARD_LIMIT": "2627731456"
    }, 
    "linuxmuster-global": {
      "FULL_USER": "UNPEUD\\dr                     ", 
      "USED": "350248960", 
      "SOFT_LIMIT_MiB": 2004.8, 
      "HARD_LIMIT_MiB": 2506, 
      "SOFT_LIMIT": "2102184960", 
      "USED_MiB": 334, 
      "HARD_LIMIT": "2627731456"
    }

and : 

    # sophomorix-user -u USER -iv | grep Quota                                   
               sophomorixQuota: default-school:2506:2506:2627731456:---:
               sophomorixQuota: linuxmuster-global:654:654:685768704:blabla:

As you can see, the `HARD_LIMIT_MiB` for `linuxmuster-global` ist not the same ( 2506 and 654, 654 is set in `school.conf` ).

Cheers,

Arnaud

**Comment by kiarn** [comment]
... or must be the quota for linuxmuster-quota always bigger than default-school ?

**Comment by jeffbeck** [comment]
no, there is no connection between the quota.
Do you have a history for what has been done here?

The difference between the commands is:
`sophomorix-user` displays AD attribute content. Therefore no info about quota usage is provided,
`sophomorix-query ... --quota-usage
` asks the smb share for what is really set on the share.

The two can differ, when you forget to call `sophomorix-quota` to actually set the quota on the smb share.

Maybe you just forget to call  `sophomorix-quota`

I made a fix because   `sophomorix-quota` is not working correctly, see #81

**Comment by kiarn** [comment]
The fix for #81, but I still have a problem with this. I didn't forget to run a `sophomorix-quota`.
Thank you for your explanations, I can better understand what's going on.
After doing your commands in #81 I got : 

```
$ sophomorix-user -u USER -iv | grep sophomorixQuota       
               sophomorixQuota: default-school:---:2506:2627731456:---: 
               sophomorixQuota: linuxmuster-global:---:711:745537536:---:
```
It's fine, then I want to give a non default quota : 

```
$ sophomorix-user --quota linuxmuster-global:789:blabla -u
$ sophomorix-quota
$ sophomorix-user -u USER -iv | grep sophomorixQuota
               sophomorixQuota: default-school:---:2506:2627731456:---: 
               sophomorixQuota: linuxmuster-global:789:789:827326464:blabla
```

Ok, let's see with `sophomorix-query` : 

```
$ sophomorix-query --sam dr --user-full --quota-usage -j
         "QUOTA_USAGE_BY_SHARE" : {
            "linuxmuster-global" : {
               "FULL_USER" : "UNPEUD\\dr                     ",
               "SOFT_LIMIT_MiB" : 631.2,
               "SOFT_LIMIT" : "661860352",
               "HARD_LIMIT_MiB" : 789,
               "USED" : "350248960",
               "HARD_LIMIT" : "827326464",
               "USED_MiB" : 334
            },
            "default-school" : {
               "USED" : "350248960",
               "HARD_LIMIT_MiB" : 789,
               "SOFT_LIMIT" : "661860352",
               "FULL_USER" : "UNPEUD\\dr                     ",
               "SOFT_LIMIT_MiB" : 631.2,
               "USED_MiB" : 334,
               "HARD_LIMIT" : "827326464"
            }
```

It should have been 2506 for `HARD_LIMIT_MiB` in `default_school` or do I misunderstand something ?

**Comment by jeffbeck** [comment]
Is your partition setup OK?

`# net conf list`

[linuxmuster-global]
	path = /srv/samba/global
	comment = Share for school global
	guest ok = yes
	read only = no

[default-school]
	path = /srv/samba/schools/default-school
	comment = Share for school default-school
	guest ok = yes
	read only = no

EACH path must end on ONE partition, with quota enable by linux

if BOTH end in THE SAME partition, the effect above occurs: change one, and the other changes as well

LG Rüdiger

**Comment by kiarn** [comment]
Ok, thanks, I got the iso from the wiki in which both paths are mounted on the same partition.
So, it can be closed.
