### ISSUE TITLE
Json output for sophomorix-quota -n

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/sophomorix4#90]
Hello @jeffbeck ,

Currently, the quota page in the webui is retrieving all quotas from alls users, and this is extremely slow with 900 users. A better approach would be for me to get the users with non-default quota, and let the others appear with default values in `school.conf`.
Problem : I can only get these informations from `sophomorix-quota -n`, but not as json format.

Is it possible to build a json output for `sophomorix-quota -n` ? 
Or is there a better solution ?

Thanks !

Arnaud

**Comment by jeffbeck** [comment]
Do you want to display the quota limit? (This is stored in an attribute)

Or do you want to display quota usage (That is slow, because the smb server has to be asked for each user)

**Comment by kiarn** [comment]
Only the quota limit, and only for non-default values.

**Comment by jeffbeck** [comment]
Hello kiarn,

I looked into this.

Please try
`sophomorix-quota -ij`

and go to the subsection NONDEFAULT_QUOTA in the json object.

In 3.73.0 I will add more data  in the object.

LG jeffbeck

**Comment by kiarn** [comment]
Thank you @jeffbeck !

The concerned dict/hash in NONDEFAULT_QUOTA gives an empty dict for mostly user, which are not concerned with non default quota, is it possible to remove these ?
Python have to scan the whole hash ( as a string ) and then can convert this as a dict. Removing the empty dicts would accelerate the process.

Secondly, it would be great if you can add firstname/lastname/role(/class if student ).

Cheers 

Arnaud

**Comment by jeffbeck** [comment]
I added the requested Values in 3.73.1 which I uploaded already

**Comment by kiarn** [comment]
Thank you !
