### ISSUE TITLE
Missing JSON Output in sophomorix-check

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/sophomorix4#93]
Hey there,

I just ran into another important error which needs json output.

If a user already exists we get this helpful message in CLI

![grafik](https://user-images.githubusercontent.com/26460239/67278495-5f8a1700-f4c9-11e9-8dc3-ab825757d6c7.png)

But there is no json output at all.
This makes it impossible for webui to show what is wrong.

**Comment by PLanB2008** [comment]
A similiar error appears when we do not provide a username for a teacher and we do not have configured auto login creation:

![grafik](https://user-images.githubusercontent.com/26460239/73250359-07913980-41b7-11ea-808f-5d0db35eab61.png)

If you could provide some json error output we could create an error message for this.

**Comment by PLanB2008** [comment]
loginname not all in lowercase letters.

**Comment by PLanB2008** [comment]
add json error output to this as well:

sophomorix-print --school default-school --caller global-admin --class 05a -jj


If empty class you receive this error:

ERROR: Class 05a has no printout data in school default-school

**Comment by jeffbeck** [comment]
sophomorix-check should always exit with json eror from 3.74.9 or later

**Comment by jeffbeck** [comment]
sophomorix-print should exist with json error frim 3.74.11 or later

**Comment by kiarn** [comment]
Thanks !
