### ISSUE TITLE
Diverse about quotas

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/sophomorix4#96]
Hello @jeffbeck,

Just 2 quick questions about quotas : 

1.  I have in my old `school.conf` only the role sections for student, teacher and schooladministrator, but not globaladministrator. Is it necessary to add a section `[role.globaladministrator]` to set the default quota for globaladmins, or do they use the same quota config as the schooladmins ?

2. Can you confirm that the cloudquota percentage can only be set globally for a role and not individually ? ( I mean, it's not possible to set 120% cloud quota only for student frayka ).

Thanks

Arnaud

**Comment by jeffbeck** [comment]
1.
globaladmins are not considered part of a school, so a section [role.globaladministrator] should throw an config error.
I guess they are created with unlimited quota. The only way to set a quota ist with ... i dont know sohomrix-user or sophomorix-admin

2. 
With the percentage value it is like this:
USE it, then the cloud space is coupled via the percentage to harddisk quota
Leave it, then you use Nextcloud tools to set cloud quota

**Comment by kiarn** [comment]
Thanks !
